---
title: "Stat 297 Homework 2"
author: "Eric, Sidharth, Kaiyi, Kai"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Question 1: Fizz Buzz
```{r}
for (i in 1:100) {
  if (i %% 3 == 0 & i %% 5 == 0) {print("Fizz Buzz")}
  else if (i %% 3 == 0) {print("Fizz")}
  else if (i %% 5 == 0) {print("Buzz")}
  else print(i)
}
```


### Question 2: Map
```{r}
install.packages("ggmap")
install.packages('rvest')
library(maps)
library(ggmap)
library(rvest)

# Define webpage
big10 = read_html("http://www.bigten.org/library/stats/fb-confsked.html#standings")

# Get uni names
big10 %>% 
  html_nodes(".b1gfbstats:nth-child(9) td:nth-child(1) , .b1gfbstats:nth-child(6) td:nth-child(1)") %>% 
  html_text() -> uni_name
uni_name = paste(uni_name,"University")

# Find uni locations
uni_coord = data.frame(geocode(uni_name))

# Get win rate
big10 %>% 
  html_nodes("td:nth-child(7)") %>%
  html_text() -> uni_wp
uni_coord$wp = 100*as.numeric(uni_wp[1:length(uni_name)])

# Get division
uni_coord$conf = rep(c("East Division","West Division"), each = length(uni_name)/2)

library(mapproj)
map <- get_map(data = uni_coord, zoom = 4)
ggmap(map) + geom_point(data = uni_coord, 
                        aes(lon, lat, col = conf, size = wp)) + 
  scale_size(name="Big 10 Conference") + 
  xlab("Longitude") + ylab("Latitude")

```

###Question 3: 3D Random Walks
***part (a):***
  
```{r}
library(plot3D)
x0 = c(0,0,0)
B = 10^4
set.seed(1982)
Ut <- runif(B)
head(Ut)

walk_fun = function(u){
  if(u<=1/6){
    fu = c(1,0,0)
  } else if (u > 1/6 & u <=1/3){
    fu = c(-1,0,0)
  }else if (u>1/3 & u<=1/2){
    fu = c(0,1,0)
  }else if(u>1/2 & u<=2/3){
    fu = c(0,-1,0)
  }else if(u >2/3 & u<=5/6){
    fu = c(0,0,1)
  }else{
    fu = c(0,0,-1)
  }
}
x = array(NA, dim = c(3,B))
for(i in 1:B){
  x[,i] = x0 + walk_fun(Ut[i])
  x0 = x[,i]
}

segments3D(x[1,], x[2,], x[3,], ticktype = "detailed")
scatter3D(x0[1], x0[2],x0[3], col ="red",  add=TRUE)
scatter3D(x[1,B], x[2,B],x[3,B], col ="blue",  add=TRUE)
```

***part (b):***
```{r}
x0 = c(0,0,0)
B = 10^5
set.seed(2000)
Ut <- runif(B)
head(Ut)

walk_fun = function(u){
  if(u<=1/6*0.99){
    fu = c(1,0,0)
  } else if (u > 1/6*0.99 & u <=1/3*0.99){
    fu = c(-1,0,0)
  }else if (u>1/3*0.99 & u<=1/2*0.99){
    fu = c(0,1,0)
  }else if(u>1/2*0.99 & u<=2/3*0.99){
    fu = c(0,-1,0)
  }else if(u >2/3*0.99 & u<=5/6*0.99){
    fu = c(0,0,1)
  }else{
    fu = c(0,0,-1)
  }
}
x = array(NA, dim = c(3,B))
for(i in 1:B){
  x[,i] = x0 + walk_fun(Ut[i])
  x0 = x[,i]
}
segments3D(x[1,], x[2,], x[3,], ticktype = "detailed")
scatter3D(x0[1], x0[2],x0[3], col ="red",  add=TRUE)
scatter3D(x[1,B], x[2,B],x[3,B], col ="blue",  add=TRUE)
```


***part (c):***
$$
  \mathbb{E}[X_B]  = \mathbb{E}[\sum_{i=1}^{B}f(U_t)] = B\cdot \mathbb{E}[f(U_t)].\\
$$
  
$$
  \begin{aligned}
\mathbb{E}[f(U_t)] &= \sum_{i=0}^{6}f(U_i)\cdot \text{Pr} (f(U_i))\\
&=  
  \begin{bmatrix}
1\\ 
0\\ 
0
\end{bmatrix}
\cdot \frac{1}{6}\cdot 0.99 +
  \begin{bmatrix}
-1\\ 
0\\ 
0
\end{bmatrix}
\cdot\frac{1}{6}\cdot 0.99+
  \begin{bmatrix}
0\\ 
1\\ 
0
\end{bmatrix}
\cdot\frac{1}{6}\cdot 0.99+
  \begin{bmatrix}
0\\ 
-1\\ 
0
\end{bmatrix}
\cdot\frac{1}{6}\cdot 0.99 \\
&+\begin{bmatrix}
0\\ 
0\\ 
1
\end{bmatrix}
\cdot\frac{1}{6}\cdot 0.99+
  \begin{bmatrix}
0\\ 
0\\ 
-1
\end{bmatrix}
\cdot [1 - \frac{5}{6}\cdot 0.99]\\
&=\begin{bmatrix}
0\\ 
0\\ 
1
\end{bmatrix}
\cdot\frac{1}{6}\cdot 0.99+
  \begin{bmatrix}
0\\ 
0\\ 
-1
\end{bmatrix}
\cdot [0.01 - \frac{1}{6} \cdot 0.99] 
=\begin{bmatrix}
0\\ 
0\\ 
-0.01
\end{bmatrix}
\end{aligned}
$$
$$
  \mathbb{E}[X_B]=
  \begin{bmatrix}
0\\ 
0\\ 
-0.01B
\end{bmatrix}
$$
  
###Question 4: Construct a portfolio
```{r}  
library(quantmod)

# Download data
today <- Sys.Date()
three_years_ago <- seq(today, length = 2, by = "-3 year")[2]
getSymbols("AAPL", from = three_years_ago, to = today)
getSymbols("NFLX", from = three_years_ago, to = today)
getSymbols("CSX", from = three_years_ago, to = today)
getSymbols("SJM", from = three_years_ago, to = today)

# Compute returns
Ra <- na.omit(ClCl(AAPL))
Rn <- na.omit(ClCl(NFLX)) 
Rc <- na.omit(ClCl(CSX))
Rs <- na.omit(ClCl(SJM))

R = list(Ra, Rn, Rc, Rs)

n = 4 ## number of stocks to choose from 
total = 1000000
exe_fee_limit = 100

for (i in 1:n){
 for(j in 1:i){
   if(i !=j){
     # Estimation of mu and Sigma
     Sigma = cov(cbind(R[[i]],R[[j]]))
     mu = c(mean(R[[i]]), mean(R[[j]]))
     # Compute omega^*
     omega_star = (Sigma[2, 2] - Sigma[1, 2])/(Sigma[1, 1] + Sigma[2, 2] - 2*Sigma[1, 2])
     # Compute investment expected value and variance
     mu_investment = omega_star*mu[1] + (1 - omega_star)*mu[2]
     var_investment = omega_star^2*Sigma[1,1] + (1 - omega_star)^2*Sigma[2,2] + 
       2*omega_star*(1 - omega_star)*Sigma[1,2]
     exe_fee =max(c(40, 0.0001*1000000*omega_star))+max(c(40, 0.0001*100000*(1-omega_star))) 
     if(exe_fee <= 100){
       cat("investing on ", i, " and ", j, "with variance", var_investment)
     }
   }
  }
}


 
```
